name: Deployment to ECS

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: petros
    steps:
      - name: Build new image
        uses: actions/checkout@v3
        run: |
          echo "Hello World"
